### ISSUE TITLE
only can take the first file from wild card file path match

### ISSUE THREAD

**Issue by playerjamesbattleground** [Ne4istb/postman-combine-collections#1]
Hello there,

Thanks for making this module and it will help us if this issue is addressed:

We have multiple collection json files under the same folder, so my `-f` arg looks like

-f /foo/bar/*.json 

and it always only take the first file in the folder.

I've observed the program object and found commander parses the wild card match before send it into the processFiles method, therefore it thinks only the first file path is the value for `-f` and the rest file paths are `args`. Here is the partial print out of the program object in the code

    `name: 'Root collection',
  output: './root.collection.json',
  _description: 'A command line tool to combine several Postman collections into one',
  rawArgs:
   [ '/usr/local/Cellar/node/7.7.2/bin/node',
     '/Users/jamjiang/workspace/studio_ws/ws_mlc/postman-combine-collections/index.js',
     '-f',
     '/Users/jamjiang/workspace/studio_ws/ws_mlc/smoke-test/integration-dev/npas-smoketest-collection.json',
     '/Users/jamjiang/workspace/studio_ws/ws_mlc/smoke-test/integration-dev/recm-smoketest-collection.1.json',
     '/Users/jamjiang/workspace/studio_ws/ws_mlc/smoke-test/integration-dev/recm-smoketest-collection.json' ],
  filePath: '/Users/jamjiang/workspace/studio_ws/ws_mlc/smoke-test/integration-dev/npas-smoketest-collection.json',
  args:
   [ '/Users/jamjiang/workspace/studio_ws/ws_mlc/smoke-test/integration-dev/recm-smoketest-collection.1.json',
     '/Users/jamjiang/workspace/studio_ws/ws_mlc/smoke-test/integration-dev/recm-smoketest-collection.json' ] }`

**Comment by Ne4istb** [comment]
Hi @Kapaski 

I've tested this tool on Windows and OS X. 
Indeed, when you use something like
```
-f /foo/bar/*.json
```
on OS X (probably, other Unix based OS) only first file will be returned instead of all. On Windows it works fine. Looks like glob util works in this way.

The workaround is to put pattern into quotes
```
-f '/foo/bar/*.json'
```

Please, check if it works for you. Anyway, I will leave this issue open and will try to solve the problem a bit later when will have time :)

**Comment by pietrangelo** [comment]
I' had the same problem on *nix environments and solved with the long version --filePath=[your_path]/*.json

**Comment by Ne4istb** [comment]
It's because of bash wildcard expansion. The tool received already resolved parameters, but according to default rules, it's the first file. Check this StackOverflow question for more details:
https://stackoverflow.com/questions/11456403/stop-shell-wildcard-character-expansion

So the suggestion is the same:
```bash
$ # quote it
$ -f '/foo/bar/*.json'

$ # or escape it
$ -f /foo/bar/\*.json

$ # or disable the glob (noglob)
$ set -f
$ -f /foo/bar/*.json
```
